# Generated by Django 4.0.5 on 2022-06-09 16:31

from django.db import migrations
import rentapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0005_user_phone_number'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', rentapp.models.UserManager()),
            ],
        ),
    ]
